# config/packages/fos_user.yaml
fos_user:
    db_driver: orm # other valid values are 'mongodb' and 'couchdb'
    firewall_name: main
    user_class: App\Entity\FosUser
    from_email:
        address: "test@domain.com"
        sender_name: "test@domain.com"

    resetting:
        email:
            from_email:
                address:        abc@gmail.com
                sender_name:    Demo Resetting
                