<?php

// This file was generated by running "composer dump-env prod"

return array (
  'APP_ENV' => 'prod',
  'APP_SECRET' => '86494f726dedfd9fab57ec3410784c47',
  'DATABASE_URL' => 'mysql://ndmcD:P@$$w0rd!!@172.21.6.14:3306/ephi',
  'GMAIL_USERNAME' => 'ethiopiannationaldata@gmail.com',
  'GMAIL_PASSWORD' => 'lgeLaN0922$!',
  'MAILER_DSN' => 'smtp://ethiopiannationaldata@gmail.com:lgeLaN0922$!@gmail',
);
